services:
  rabbitmq:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: scothtiger
      RABBITMQ_DEFAULT_PASS: 123456
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=secretsmanager
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack/data
    volumes:
      - localstack_data:/var/lib/localstack

  baget:
    image: loicsharma/baget:latest
    ports:
      - "5000:80"
    environment:
      - Baget__Database__Type=Sqlite
      - Baget__Database__ConnectionString=Data Source=/var/baget/baget.db
      - Baget__Storage__Type=FileSystem
      - Baget__Storage__Path=/var/baget/packages
    volumes:
      - baget_data:/var/baget

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: somew0rds
      POSTGRES_DB: GamersWorldDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: scoth@tiger.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "5050:80"
    depends_on:
      - postgres

  consul:
    image: hashicorp/consul:latest
    ports:
      - '8500:8500'
  
  ftp-server:
    image: delfer/alpine-ftp-server
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    environment:
      FTP_USER: "userone"
      FTP_PASS: "123"
      PASV_MIN_PORT: 21000
      PASV_MAX_PORT: 21010
    volumes:
      - ftp_data:/home/ftpuser/ftp_data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    environment:
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - elk-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.3
    ports:
      - "5601:5601"
    environment:
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: 9939746F-B0B9-49C2-BB04-B695241D4881
    depends_on:
      - elasticsearch
    networks:
      - elk-network

  audit-web-api:
    image: systemhome/evalapi
    ports:
      - "5147:8080"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=123456
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  localstack_data:
  baget_data:
  postgres_data:
  ftp_data:
  es_data:
  grafana-storage:
  
networks:
  elk-network:
    driver: bridge