services:
  rabbitmq:
    image: rabbitmq:management
    container_name: dc-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: scothtiger
      RABBITMQ_DEFAULT_PASS: 123456
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - dc-network

  redis:
    image: redis:latest
    container_name: dc-redis
    ports:
      - "6379:6379"
    networks:
      - dc-network

  localstack:
    image: localstack/localstack:latest
    container_name: dc-localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=secretsmanager
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack/data
    volumes:
      - localstack_data:/var/lib/localstack
    networks:
      - dc-network

  baget:
    image: loicsharma/baget:latest
    container_name: dc-baget
    ports:
      - "5000:80"
    environment:
      - Baget__Database__Type=Sqlite
      - Baget__Database__ConnectionString=Data Source=/var/baget/baget.db
      - Baget__Storage__Type=FileSystem
      - Baget__Storage__Path=/var/baget/packages
    volumes:
      - baget_data:/var/baget
    networks:
      - dc-network

  postgres:
    image: postgres:latest
    container_name: dc-postgres
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: somew0rds
      POSTGRES_DB: GamersWorldDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data
    networks:
      - dc-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: dc-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: scoth@tiger.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - dc-network

  consul:
    image: hashicorp/consul:latest
    container_name: dc-consul
    ports:
      - '8500:8500'
    networks:
      - dc-network
  
  ftp-server:
    image: delfer/alpine-ftp-server
    container_name: dc-ftp-server
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    environment:
      FTP_USER: "userone"
      FTP_PASS: "123"
      PASV_MIN_PORT: 21000
      PASV_MAX_PORT: 21010
    volumes:
      - ftp_data:/home/ftpuser/ftp_data
    networks:
      - dc-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    container_name: dc-elasticsearch
    environment:
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - dc-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.3
    container_name: dc-kibana
    ports:
      - "5601:5601"
    environment:
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: 9939746F-B0B9-49C2-BB04-B695241D4881
    depends_on:
      - elasticsearch
    networks:
      - dc-network

  audit-web-api:
    image: systemhal/evalapi
    container_name: dc-audit-web-api
    ports:
      - "5147:8080"
    networks:
      - dc-network

  prometheus:
    image: prom/prometheus:latest
    container_name: dc-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - dc-network
    extra_hosts:
      - "host.docker.internal:host-gateway" # Added for accessing localhost metric servers

  grafana:
    image: grafana/grafana:latest
    container_name: dc-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=123456
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - dc-network
  
  sonarqube:
    image: sonarqube:latest
    container_name: dc-sonarqube
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    ports:
      - "9000:9000"
    networks:
      - dc-network

volumes:
  localstack_data:
  baget_data:
  postgres_data:
  ftp_data:
  es_data:
  grafana-storage:
  
networks:
  dc-network:
    driver: bridge
